server:
  port: 9192

spring:
  cloud:
    stream:
      function:
        definition: orderEventPublisher; orderEventSubscriber; paymentEventSubscriber
      bindings:
        orderEventPublisher-out-0:
          destination: order-events
        orderEventProcessor-in-0:
          destination: order-events
        orderEventProcessor-out-0:
          destination: payment-events
        paymentEventConsumer-in-0:
          destination: payment-events
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
