server:
  port: 9191

spring:
  cloud:
    stream:
      function:
        definition: orderPurchaseEventProcessor;paymentEventSubscriber
      bindings:
        orderPurchaseEventProcessor-in-0:
          destination: orders
        orderPurchaseEventProcessor-out-0:
          destination: payments
        paymentEventSubscriber-in-0:
          destination: payments
        paymentEventSubscriber-out-0:
          destination: transactions
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: true
