server:
  port: 9191

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: payment
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect